import { Selectable, SelectableButtonsWithSave, Tab } from "common.slint";

export component PresetsTab inherits Tab {
    in property <[Selectable]> presets: [
        {name:"my preset", selected: true, removable: true},
        {name:"other"},
        {name:"other"},
        {name:"other"},
        {name:"other"},
        {name:"other"},
        {name:"last"},
    ];
    callback select-preset <=> btns.select-clicked;
    callback delete-preset <=> btns.delete-clicked;
    callback save-preset <=> btns.save-clicked;

    btns := SelectableButtonsWithSave {
        height: 100%;
        width: 100%;
        options: presets;
    }
}