import { Pitches, TouchButton, Group, GL, Style, HL, Tab} from "common.slint";
import { EditMode , KeyboardFooter} from "keyboard.slint";
import { UIState } from "state.slint";

component OctaveSelector inherits HL {
    in property <int> octave;
    callback clicked(int);
    for octave in [0,1,2,3,4]: TouchButton  {
        text: octave;
        checked: octave == root.octave;
        clicked => {clicked(octave)}
    }
}

component PitchSelector inherits Rectangle {
    in property <int> pitch;
    callback clicked(int);
    property <length> spacing: Style.area-spacing;
    padding: Style.area-padding;
    property <length> button-width: self.width / 4;
    property <length> button-height: self.height / 3;
    property <[[int]]> pitches: [
        [0,1,2,3],
        [4,5,6,7],
        [8,9,10,11]
    ];

    for row-pitches[row] in pitches: Rectangle {
        for pitch[col] in row-pitches: TouchButton {
            x: col * button-width + spacing / 2;
            width: (button-width - spacing);
            y: row * button-height + spacing / 2;
            height: (button-height - spacing);
            text: Pitches.pitches[pitch].text;
            checked: root.pitch == pitch;
            clicked => {clicked(pitch)}
        }
    }
}

export component RootTab inherits Tab {
    property <float> button-stretch: 0.5;
    property <float> text-stretch: 0.1;
    GL {
        Group {
            col: 0;
            row: 0;
            rowspan: 3;
            name: "Root Note";
            PitchSelector {
                vertical-stretch: 1;
                pitch: UIState.root-pitch;
                clicked(n) => {UIState.root-pitch-clicked(n)}
            }
        }

        Group {
            col: 1;
            row: 0;
            name: "Lead Octave";
            OctaveSelector {
                vertical-stretch: button-stretch;
                octave: UIState.lead-octave;
                clicked(o) => {UIState.lead-octave-clicked(o)}
            }
        }
        Group {
            col: 1;
            row: 1;
            name: "Guitar Octave";
            OctaveSelector {
                vertical-stretch: button-stretch;
                octave: UIState.guitar-octave;
                clicked(o) => {UIState.guitar-octave-clicked(o)}
            }
        }
        Group {
            col: 1;
            row: 2;
            name: "Drone Octave";
            OctaveSelector {
                vertical-stretch: button-stretch;
                octave: UIState.drone-octave;
                clicked(o) => {UIState.drone-octave-clicked(o)}
            }
        }
        KeyboardFooter {
            clicked(n) => {UIState.root-pitch-clicked(n)}
            row: 3;
            colspan: 2;
            edit-mode: EditMode.Root;
        }
    }
}