import { Tab, Selectable, SelectableButtonsWithSave, VL} from "common.slint";
import { EditMode , KeyboardFooter} from "keyboard.slint";

export component ScaleTab inherits Tab {
    callback clicked <=> kb.clicked;
    in property <[bool]> scale-notes <=> kb.scale-notes;
    in property <[float]> leads <=> kb.leads;
    in property <[float]> drones <=> kb.drones;
    in property <int> root-pitch <=> kb.root-pitch;

    in property <[Selectable]> scale-presets: [];
    callback select-scale <=> btns.select-clicked;
    callback delete-scale <=> btns.delete-clicked;
    callback save-scale <=> btns.save-clicked;

    VL {
        btns := SelectableButtonsWithSave {
            options: scale-presets;
        }

        kb := KeyboardFooter {
            edit-mode: EditMode.Scale;
        }
    }
}