import { CaptionedFader, Tab , Group, HL} from "common.slint";

export component MixTab inherits Tab {
    in-out property mix-lead <=> lead.value;
    in-out property mix-guitar <=> guitar.value;
    in-out property mix-drone <=> drone.value;
    in-out property mix-master <=> master.value;
    

    callback mix-lead-changed <=> lead.changed;
    callback mix-guitar-changed <=> guitar.changed;
    callback mix-drone-changed <=> drone.changed;
    callback mix-master-changed <=> master.changed;

    
    HL {
        alignment: LayoutAlignment.space-around;
        Group {
            HL {
                lead := CaptionedFader {
                    text: "Lead";
                }
                guitar := CaptionedFader {
                    text: "Guitar";
                }
                drone := CaptionedFader {
                    text: "Drone";
                }
            }
        }
        Group {
            HL {
                master := CaptionedFader {
                    text: "Master";
                }
            }
        }
    }
}