import { Selectable, SelectableButtonsWithSave, Tab , GL} from "common.slint";

export component PresetsTab inherits Tab {
    in property <[Selectable]> presets <=> btns.options;
    callback select-preset <=> btns.select-clicked;
    callback delete-preset <=> btns.delete-clicked;
    callback save-preset <=> btns.save-clicked;

    GL {
        btns := SelectableButtonsWithSave {}
    }
}