import { Tab, Group, TextTouchButton, VL, HL} from "common.slint";
import { Handedness } from "types.slint";
import { UIState } from "state.slint";

export component SettingsTab inherits Tab {
    VL {
        Group {
            name: "System";
            VL {
                TextTouchButton {
                    text: "Fullscreen";
                    checked: UIState.fullscreen;
                    clicked => {UIState.fullscreen-clicked()}
                }
                TextTouchButton {
                    text: "High Priority Process";
                    checked: UIState.high-priority;
                    clicked => {UIState.high-priority-clicked()}
                }
                TextTouchButton {
                    text: "On-screen keyboard";
                    checked: UIState.use-on-screen-keyboard;
                    clicked => {UIState.on-screen-kbd-clicked()}
                }
            }
        }

        Group {
            name: "Handedness";
            HL { 
                TextTouchButton { 
                    text: "Left Handed";
                    checked: UIState.handedness == Handedness.LeftHanded;
                    clicked => {UIState.lh-clicked()}
                }
                TextTouchButton {
                    text: "Right Handed";
                    checked: UIState.handedness == Handedness.RightHanded;
                    clicked => {UIState.rh-clicked()}
                }
            }
        }
    }
}