import { Selectable, SelectableButtonsWithSave, Tab } from "common.slint";

export component PresetsTab inherits Tab {
    in property <[Selectable]> presets: [];
    callback select-preset <=> btns.select-clicked;
    callback delete-preset <=> btns.delete-clicked;
    callback save-preset <=> btns.save-clicked;

    btns := SelectableButtonsWithSave {
        height: 100%;
        width: 100%;
        options: presets;
    }
}