import { Tab, SelectableButtonsWithSave, VL} from "common.slint";
import { EditMode , KeyboardFooter} from "keyboard.slint";
import { Selectable } from "types.slint";
import { UIState } from "state.slint";

export component ScaleTab inherits Tab {
    VL {
        SelectableButtonsWithSave {
            options: UIState.scale-presets;
            select-clicked(s) => {UIState.select-scale(s)}
            delete-clicked(s) => {UIState.delete-scale(s)}
            save-clicked(s) => {UIState.save-scale(s)}
        }

        KeyboardFooter {
            edit-mode: EditMode.Scale;
            clicked(n) => {UIState.scale-clicked(n)}
        }
    }
}