import { CaptionedFader, Tab , Group, HL } from "common.slint";
import { UIState } from "state.slint";

export component MixTab inherits Tab {
    HL {
        alignment: LayoutAlignment.space-around;
        Group {
            HL {
                lead := CaptionedFader {
                    text: "Lead";

                    value: UIState.mix-lead;
                    changed(v) => {UIState.mix-lead-changed(v)}
                    minimum: UIState.mix-lead-control.min;
                    maximum: UIState.mix-lead-control.max;

                }
                guitar := CaptionedFader {
                    text: "Guitar";

                    value: UIState.mix-pluck;
                    changed(v) => {UIState.mix-pluck-changed(v)}
                    minimum: UIState.mix-pluck-control.min;
                    maximum: UIState.mix-pluck-control.max;
                }
                drone := CaptionedFader {
                    text: "Drone";

                    value: UIState.mix-drone;
                    changed(v) => {UIState.mix-drone-changed(v)}
                    minimum: UIState.mix-drone-control.min;
                    maximum: UIState.mix-drone-control.max;
                }
            }
        }
        Group {
            HL {
                master := CaptionedFader {
                    text: "Master";

                    value: UIState.mix-master;
                    changed(v) => {UIState.mix-master-changed(v)}
                    minimum: UIState.mix-master-control.min;
                    maximum: UIState.mix-master-control.max;
                }
            }
        }
    }
}